"""Portfolio archive of the original 512+1, 2+7 experiment.

The training loop evaluates the test loader every epoch and selects a checkpoint
on test accuracy. Stored metrics are historical development results. Replace the
hard-coded Google Drive paths and use a validation split for a rigorous rerun.
"""

# -*- coding: utf-8 -*-
"""(2+7)final_code for pneumonia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GZB4-1bc5NngMlel0y3yHs7gGhPJ90fi
"""

# ================================================================
# 0. Install required libraries
# ================================================================
# Colab setup command (run in a notebook cell):
# %pip install -q numpy pandas scikit-learn matplotlib seaborn torch torchvision \
#     qiskit qiskit-machine-learning qiskit-aer imbalanced-learn tqdm

# ================================================================
# 1. Imports & Setup (QISKIT-SAFE)
# ================================================================
import os, random, math
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image
from tqdm import tqdm
from collections import Counter

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, models

# -------- QISKIT (V2 ONLY — VERY IMPORTANT) --------
from qiskit.circuit.library import zz_feature_map, real_amplitudes
from qiskit.primitives import StatevectorEstimator
from qiskit_machine_learning.neural_networks import EstimatorQNN
from qiskit_machine_learning.connectors import TorchConnector

# -------- Metrics --------
from sklearn.metrics import classification_report, confusion_matrix

# 2. Reproducibility
def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_seed(42)
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)

# 3. Mount Google Drive & Load Dataset
from google.colab import drive
import zipfile

drive.mount('/content/drive')
zip_path = "/content/drive/MyDrive/chest_xray.zip"
extract_path = "/content/MyDrive/chest_xray"

if not os.path.exists(extract_path):
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(extract_path)
print("Dataset ready at:", extract_path)

# ================================================================
# 4. Merge train+test+val → Balance → 80–20 Split (ROBUST)
# ================================================================
import shutil
from sklearn.model_selection import train_test_split

set_seed(42)

# --- FIND ACTUAL BASE DIRECTORY ---
base = extract_path

# Handle nested extraction like chest_xray/chest_xray
if os.path.isdir(os.path.join(base, "chest_xray")):
    base = os.path.join(base, "chest_xray")

print(" Using base dataset path:", base)

# Detect correct class folder names automatically
def find_class_dir(parent, class_name):
    for d in os.listdir(parent):
        if d.lower() == class_name.lower():
            return os.path.join(parent, d)
    raise FileNotFoundError(f"{class_name} not found in {parent}")

normal_dirs = []
pneumonia_dirs = []

for split in ["train", "test", "val"]:
    split_path = os.path.join(base, split)
    normal_dirs.append(find_class_dir(split_path, "normal"))
    pneumonia_dirs.append(find_class_dir(split_path, "pneumonia"))

# Collect image paths
normal_imgs = []
for d in normal_dirs:
    normal_imgs += [os.path.join(d, f) for f in os.listdir(d)]

pneumonia_imgs = []
for d in pneumonia_dirs:
    pneumonia_imgs += [os.path.join(d, f) for f in os.listdir(d)]

print("Original counts → Normal:", len(normal_imgs),
      "Pneumonia:", len(pneumonia_imgs))

# ------------------ BALANCING ------------------
pneumonia_imgs = random.sample(pneumonia_imgs, len(normal_imgs))

# ------------------ SPLIT ------------------
norm_train, norm_test = train_test_split(
    normal_imgs, test_size=0.2, random_state=42)

pneu_train, pneu_test = train_test_split(
    pneumonia_imgs, test_size=0.2, random_state=42)

# Output folders
balanced_base = "/content/balanced_chest_xray"
train_dir = f"{balanced_base}/train"
test_dir  = f"{balanced_base}/test"

for cls in ["NORMAL", "PNEUMONIA"]:
    os.makedirs(f"{train_dir}/{cls}", exist_ok=True)
    os.makedirs(f"{test_dir}/{cls}", exist_ok=True)

def copy_files(files, dst):
    for f in files:
        shutil.copy(f, dst)

copy_files(norm_train, f"{train_dir}/NORMAL")
copy_files(norm_test,  f"{test_dir}/NORMAL")
copy_files(pneu_train, f"{train_dir}/PNEUMONIA")
copy_files(pneu_test,  f"{test_dir}/PNEUMONIA")

print("Balanced dataset created ")
print("Train → Normal:", len(norm_train), "Pneumonia:", len(pneu_train))
print("Test  → Normal:", len(norm_test),  "Pneumonia:", len(pneu_test))

# ================================================================
# 5. Load Images into Memory (Balanced Dataset)
# ================================================================
img_size = (224, 224)

def load_images_from_folder(folder, label, target_size=img_size):
    data, labels = [], []
    for fname in os.listdir(folder):
        path = os.path.join(folder, fname)
        try:
            img = Image.open(path).convert("RGB").resize(target_size)
            data.append(np.array(img))
            labels.append(label)
        except:
            pass
    return data, labels

train_norm, y1 = load_images_from_folder(
    "/content/balanced_chest_xray/train/NORMAL", 0)
train_pneu, y2 = load_images_from_folder(
    "/content/balanced_chest_xray/train/PNEUMONIA", 1)

X_train = np.array(train_norm + train_pneu)
y_train = np.array(y1 + y2)

test_norm, y1t = load_images_from_folder(
    "/content/balanced_chest_xray/test/NORMAL", 0)
test_pneu, y2t = load_images_from_folder(
    "/content/balanced_chest_xray/test/PNEUMONIA", 1)

X_test = np.array(test_norm + test_pneu)
y_test = np.array(y1t + y2t)

print("Train:", X_train.shape, "Test:", X_test.shape)

#optional (sanity check)

from collections import Counter

print("Train distribution:", Counter(y_train))
print("Test distribution :", Counter(y_test))

assert Counter(y_train)[0] == Counter(y_train)[1], "Train set NOT balanced!"
assert Counter(y_test)[0] == Counter(y_test)[1], "Test set NOT balanced!"

print(" Sanity check passed: datasets are balanced")

# 5.1 . Dataset Class & DataLoaders
class ImageDataset(Dataset):
    def __init__(self, X, y, train=True):
        self.X = X
        self.y = y
        self.transform = transforms.Compose([
            transforms.ToPILImage(),
            transforms.RandomResizedCrop(224, scale=(0.8, 1.0)) if train else transforms.Resize((224, 224)),
            transforms.RandomHorizontalFlip() if train else transforms.Lambda(lambda x: x),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
        ])

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        img = self.X[idx]
        label = self.y[idx]
        img = self.transform(img)
        return img, torch.tensor(label, dtype=torch.long)

train_loader = DataLoader(ImageDataset(X_train, y_train, train=True), batch_size=16, shuffle=True)
test_loader = DataLoader(ImageDataset(X_test, y_test, train=False), batch_size=16, shuffle=False)

# ================================================================
# 6. Define Models (Baseline + Quantum) — QISKIT V2 SAFE
# ================================================================

from qiskit.circuit.library import zz_feature_map, real_amplitudes
from qiskit.primitives import StatevectorEstimator
from qiskit_machine_learning.neural_networks import EstimatorQNN
from qiskit_machine_learning.connectors import TorchConnector
from qiskit.quantum_info import SparsePauliOp


class BaselineResNet(nn.Module):
    def __init__(self, num_classes=2):
        super().__init__()
        self.model = models.resnet18(weights=models.ResNet18_Weights.DEFAULT)
        in_ftrs = self.model.fc.in_features
        self.model.fc = nn.Linear(in_ftrs, num_classes)

    def forward(self, x):
        return self.model(x)


def create_qnn(num_qubits=4, reps=2):
    feature_map = zz_feature_map(num_qubits, reps=reps)
    ansatz = real_amplitudes(num_qubits, reps=reps)
    qc = feature_map.compose(ansatz)

    estimator = StatevectorEstimator()

    observables = SparsePauliOp("Z" + "I" * (num_qubits - 1))

    qnn = EstimatorQNN(
        circuit=qc,
        estimator=estimator,
        input_params=feature_map.parameters,
        weight_params=ansatz.parameters,
        observables=observables
    )

    return TorchConnector(qnn)


class QuantumResNet(nn.Module):
    def __init__(self, num_classes=2, num_qubits=4, q_reps=2, proj_dim=8):
        super().__init__()

        self.resnet = models.resnet18(weights=models.ResNet18_Weights.DEFAULT)
        self.resnet.fc = nn.Identity()

        self.proj = nn.Linear(512, proj_dim)
        self.proj_norm = nn.LayerNorm(proj_dim)

        self.qnn = create_qnn(num_qubits=num_qubits, reps=q_reps)
        self.qnorm = nn.LayerNorm(1)

        self.fc = nn.Linear(512 + 1, num_classes)

    def forward(self, x):
        x_feat = self.resnet(x)
        q_in = torch.tanh(self.proj_norm(self.proj(x_feat)))
        q_out = self.qnorm(self.qnn(q_in))
        combined = torch.cat([x_feat, q_out], dim=1)
        return self.fc(combined)

print(type(q_model.qnn.neural_network.estimator))

# 7. Optimizer + Training Utilities
def make_optimizer(model):
    q_params = [p for n, p in model.named_parameters() if 'qnn' in n or 'proj' in n]
    base_params = [p for n, p in model.named_parameters() if not any(k in n for k in ['qnn', 'proj'])]
    optimizer = torch.optim.AdamW([
        {'params': base_params, 'lr': 3e-4},
        {'params': q_params, 'lr': 1e-3},
    ], weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=50)
    return optimizer, scheduler

# 8. Evaluation + Confusion Matrix
def evaluate(model, dataloader, device, class_names=["NORMAL", "PNEUMONIA"]):
    model.eval()
    all_preds, all_labels = [], []
    with torch.no_grad():
        for imgs, labels in dataloader:
            imgs, labels = imgs.to(device), labels.to(device)
            outputs = model(imgs)
            _, preds = outputs.max(1)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())
    acc = 100 * np.mean(np.array(all_preds) == np.array(all_labels))
    print(f"\nTest Accuracy: {acc:.2f}%")
    print(classification_report(all_labels, all_preds, target_names=class_names, digits=4))
    cm = confusion_matrix(all_labels, all_preds)
    plt.figure(figsize=(6, 5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names)
    plt.xlabel("Predicted"); plt.ylabel("True"); plt.title(f"Confusion Matrix (Acc {acc:.2f}%)")
    plt.show()
    return acc

# 9. Train Function
def train_model(model, train_loader, test_loader, device, epochs=50, warmup_epochs=5, save_path=None):
    criterion = nn.CrossEntropyLoss(label_smoothing=0.1)
    optimizer, scheduler = make_optimizer(model)
    best_acc = 0; hist = {"loss": [], "acc": [], "test_acc": []}

    if hasattr(model, "resnet"):
        print(f"\nWarm-up for {warmup_epochs} epochs...")
        for p in model.resnet.parameters(): p.requires_grad = False
        for ep in range(warmup_epochs):
            model.train(); run_loss = 0; correct = 0; total = 0
            for x, y in tqdm(train_loader, desc=f"Warmup {ep+1}/{warmup_epochs}"):
                x, y = x.to(device), y.to(device)
                optimizer.zero_grad()
                out = model(x); loss = criterion(out, y); loss.backward(); optimizer.step()
                run_loss += loss.item(); _, pred = out.max(1)
                correct += pred.eq(y).sum().item(); total += y.size(0)
            print(f"Warmup Epoch {ep+1}: Loss={run_loss/len(train_loader):.4f} Acc={100*correct/total:.2f}%")
        for p in model.resnet.parameters(): p.requires_grad = True

    print("\nFull Training...")
    for ep in range(epochs):
        model.train(); run_loss = 0; correct = 0; total = 0
        for x, y in tqdm(train_loader, desc=f"Epoch {ep+1}/{epochs}"):
            x, y = x.to(device), y.to(device)
            optimizer.zero_grad(); out = model(x); loss = criterion(out, y); loss.backward(); optimizer.step()
            run_loss += loss.item(); _, pred = out.max(1)
            correct += pred.eq(y).sum().item(); total += y.size(0)
        scheduler.step()
        train_acc = 100 * correct / total
        test_acc = evaluate(model, test_loader, device)
        hist["loss"].append(run_loss/len(train_loader)); hist["acc"].append(train_acc); hist["test_acc"].append(test_acc)
        if test_acc > best_acc and save_path:
            best_acc = test_acc; torch.save(model.state_dict(), save_path)
            print(f"Saved best model ({best_acc:.2f}%)")
        print(f"Epoch {ep+1}: Loss={run_loss/len(train_loader):.4f}, TrainAcc={train_acc:.2f}%, TestAcc={test_acc:.2f}%")
    return hist, best_acc

def plot_training(hist):
    ep = range(1, len(hist["loss"]) + 1)
    plt.figure(figsize=(12, 5))
    plt.subplot(1, 2, 1); plt.plot(ep, hist["loss"], 'r-o'); plt.title("Loss"); plt.xlabel("Epoch")
    plt.subplot(1, 2, 2); plt.plot(ep, hist["acc"], 'b-o', label="Train"); plt.plot(ep, hist["test_acc"], 'g-o', label="Test")
    plt.title("Accuracy"); plt.legend(); plt.show()

# 11. Train Quantum Hybrid ResNet
quantum_path = "/content/drive/MyDrive/best_quantum_512plus1_2w7e.pth"
q_model = QuantumResNet(num_classes=2, num_qubits=4, q_reps=2, proj_dim=4).to(device)
q_hist, q_acc = train_model(q_model, train_loader, test_loader, device, epochs=7, warmup_epochs=2, save_path=quantum_path)
plot_training(q_hist)
print("Quantum Hybrid Final Test Acc:", q_acc)

def compute_test_loss(model, dataloader, criterion, device):
    model.eval()
    total_loss = 0.0
    with torch.no_grad():
        for imgs, labels in dataloader:
            imgs, labels = imgs.to(device), labels.to(device)
            outputs = model(imgs)
            loss = criterion(outputs, labels)
            total_loss += loss.item()
    return total_loss / len(dataloader)

from sklearn.metrics import roc_curve, auc

def plot_roc_curve(model, dataloader, device):
    model.eval()
    y_true, y_score = [], []

    with torch.no_grad():
        for imgs, labels in dataloader:
            imgs = imgs.to(device)
            outputs = model(imgs)
            probs = torch.softmax(outputs, dim=1)[:, 1].cpu().numpy()
            y_score.extend(probs)
            y_true.extend(labels.numpy())

    fpr, tpr, _ = roc_curve(y_true, y_score)
    roc_auc = auc(fpr, tpr)

    plt.figure(figsize=(5,5))
    plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.4f}")
    plt.plot([0,1], [0,1], 'k--')
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")
    plt.title("ROC Curve (Test Set)")
    plt.legend(loc="lower right")
    plt.grid(True)
    plt.show()

    print("ROC AUC:", roc_auc)

plot_roc_curve(q_model, test_loader, device)
